#Êý¾Ý¿â
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: sa

#Mybatis
mybatis:
  type-aliases-package: com.yuantu.po
  mapper-locations: classpath:dataimpl/*/*Mapper.xml

